name: Powershell Analyze and Publish 

on:
  workflow_dispatch:
      inputs:
        ModuleVersion:
          description: 'Module Version'     
          required: true
          default: ''
jobs:
  build:
    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Validate Version Input
      shell: powershell
      run: |
        $version, $suffix = "${{ github.event.inputs.ModuleVersion }}" -split "-", 2
        [Version]$version
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Update Version in PSD1
      shell: powershell
      run: |
        $fileName = "${{ github.workspace }}\EnterDeveloperPowerShell\EnterDeveloperPowerShell.psd1"
        [Version]$newVersion, $newVersionSuffix = "${{ github.event.inputs.ModuleVersion }}" -split "-", 2
        $manifestContents =  Get-Content $fileName -raw
        $options = [System.Text.RegularExpressions.RegexOptions]::IgnoreCase -bor [System.Text.RegularExpressions.RegexOptions]::Multiline
        $matches = [Regex]::Matches($manifestContents, '(ModuleVersion\s*=\s*'')(.*?)(''.*$)', $options)
        [Version]$oldVersion, $oldVersionSuffix = $matches.Groups[2].Value -split "=", 2
        if ($oldVersion -lt $newVersion) {
            throw "You cannot publish an older module version to the gallery."
            exit 1
        } elseif ($oldVersion -eq $newVersion -and $oldVersionSuffix -ieq $newVersionSuffix) {
            throw "You must change the version before publishing to the gallery."
            exit 1
        }
        $manifestContents = [Regex]::Replace($manifestContents, '(ModuleVersion\s*=\s*'')(.*?)(''.*$)', "`${1}8675309`${3}", $options)
        [System.IO.File]::WriteAllText($fileName, $manifestContents)
    
    - name: Run PSScriptAnalyzer
      shell: powershell
      run: |
        Import-Module PSScriptAnalyzer
        $results = Invoke-ScriptAnalyzer -path "${{ github.workspace }}" -Recurse -Fix 
        Write-Output $results
        $errors = $results | Where-Object { $_.Severity -ieq "Warning" -or $_.Severity -ieq "Error" } 
        if ($errors -and $errors.Count -gt 0) {
          throw "Problems were found in the powershell scripts. Please fix before running this build again."
          exit 1
        }
    
    # - name: Publish Module to PowerShell Gallery
      # uses: pcgeek86/publish-powershell-module-action@v19
      # id: publish-module
      # with:
        # modulePath: EnterDeveloperPowerShell
        # NuGetApiKey: ${{ secrets.POWERSHELL_GALLERY_APIKEY }}

    - name: Commit changes  
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff-index --quiet HEAD || git commit -m "Updating changes made by build"   
    
    - name: Push changes  
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.HEAD_REF }}
        force: true

